tap "dart-lang/dart"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
brew "bat"
brew "python@3.9", link: false
brew "httpie"
brew "hugo"
brew "wget"
brew "dart-lang/dart/dart"
brew "heroku/brew/heroku"
brew "mongodb/brew/mongodb-community"
